---

- name: Install EPEL from Repo
  yum:
    name: epel-release
    state: present

- name: Install Nginx package
  yum:
    name: nginx
    state: present
  notify: restart nginx

- name: Enable service nginx
  service:
    name: nginx
    enabled: yes

- name: Change HTML
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html

- name: Create NGINX config file from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: reload nginx
  tags:
   - nginx-config
